Update generator_config.yaml
try to fix missing National keyword.

deutschland.feiertage.exceptions.ApiValueError: Invalid value for `nur_land` (NATIONAL), must be one of ['BW', 'BY', 'BE', 'BB', 'HB', 'HH', 'HE', 'MV', 'NI', 'NW', 'RP', 'SL', 'SN', 'ST', 'SH', 'TH']